spring:
  application:
    name: homecredit
  datasource:
    url: jdbc:mysql://localhost:3306/homecredit
    username: root
    password: ENC(SdGxKI3e8948Y/nfxYtRhQ==)
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8182

jasypt:
  encryptor:
    password: As2asw@sda@f
    algorithm: PBEWithMD5AndDES

---
spring:
  profiles:
    active: dev
